### ISSUE TITLE
compiled with Address Sanitizer?

### ISSUE THREAD

**Issue by hmijail** [apple/ccs-pykerberos#51]
I don't know whether this should be reported here - please let me know where to go if not.

When installing pykerberos (with pip in a Python 3.5.2 installation in macOS 10.12 Sierra), a file "kerberos.cpython-35m-darwin.so" gets installed (in my case in a venv: venv/lib/python3.5/site-packages/kerberos.cpython-35m-darwin.so). 

This .so file seems to have been compiled using clang's Address Sanitizer, and triggers this error message:
```
==78358==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
==78358==AddressSanitizer CHECK failed: /Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-800.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:690 "(("interceptors not installed" && 0)) != (0)" (0x0, 0x0)
    <empty stack>

Abort trap: 6
```
 `otool -lL kerberos.cpython-35m-darwin.so` shows that the it refers to dylib `	@rpath/libclang_rt.asan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)`, and has a load command like this:
```
Load command 17
          cmd LC_RPATH
      cmdsize 136
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib/darwin (offset 12)
```
Can you please confirm whether I got it right?

And if so, when do you plan to get out a new version not compiled with the sanitizer? :)

(note, I have tried setting the DYLD_INSERT_LIBRARIES and it doesn't work)

**Comment by dreness** [comment]
Hi @hmijail ,

Perhaps this problem is specific to python 3 - it doesn't seem to reproduce for me using 2.7:

$ python -V
Python 2.7.10

# in a virtualenv containing only pykerberos
$ pip list
pip (8.1.2)
pykerberos (1.1.13)
setuptools (17.0)
wheel (0.24.0)

$ pwd
/Users/andre/work/pytest/lib/python2.7/site-packages

$ find . -name "*.so"                  
./kerberos.so

$ otool -lL kerberos.so | grep -i clang
$

This isn't to say that it shouldn't be addressed for Python3, but that might explain why at least I didn't see it. I'll give it a try in python3 if you give it a try in python2 :)

**Comment by hmijail** [comment]
Done :). You are right, the kerberos.so installed by Python 2.7 shows no traces of asan. Interesting.

```
$ otool -lL  ~/Library/Python/2.7/lib/python/site-packages/kerberos.so | grep -i clang
```

**Comment by hmijail** [comment]
Any idea of whether there will be a new release soon-ish? Just trying to know whether I should try going back to, and pin, some previous pykerberos release...

**Comment by dreness** [comment]
Research indicates that inclusion of address sanitizer stuff is expected when using pre-release versions of Xcode. Which build are you using? The GM version is currently 8A218a. When I build pykerberos on Sierra 10.12 (16A323) using Xcode 8.0 (8A218a), I don't see the unwanted linkage to @rpath/libclang_rt.asan_osx_dynamic.dylib.

```
$ sw_vers ; python3 -V ; xcodebuild -version
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323
Python 3.5.2
Xcode 8.0
Build version 8A218a

$ pip3 list
pip (8.1.2)
pykerberos (1.1.13)
setuptools (28.0.0)
wheel (0.29.0)

$ python3 -c "import kerberos; print(kerberos)"
<module 'kerberos' from '/usr/local/lib/python3.5/site-packages/kerberos.cpython-35m-darwin.so'>
vm261:~ local$ otool -lL /usr/local/lib/python3.5/site-packages/kerberos.cpython-35m-darwin.so | grep -i clang
vm261:~ local$ 
```

**Comment by hmijail** [comment]
But I am not building pykerberos myself; I only installed it using `pip`. 

I am no Python expert, but `pip` seems to just download and install the binary. In fact, when installing pykerberos like this, `execsnoop` shows no compiler execution. 

So my guess was that the pykerberos wheel being installed by pip contained the miscompiled .so file, and I assumed that you had control over that wheel. Is it so, or should I rather go to the PyPI maintainers?

Just in case, I'll replicate your reporting:
```
$ sw_vers ; python3 -V ; xcodebuild -version
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323
Python 3.5.2
Xcode 8.0
Build version 8A218a

$ python3.5 -m venv venv1

$ . venv1/bin/activate

$ pip install pykerberos
Collecting pykerberos
Installing collected packages: pykerberos
Successfully installed pykerberos-1.1.13
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ pip list
pip (8.1.1)
pykerberos (1.1.13)
setuptools (20.10.1)

$ python3 -c "import kerberos; print(kerberos)"
==32393==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
==32393==AddressSanitizer CHECK failed: /Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-800.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:690 "(("interceptors not installed" && 0)) != (0)" (0x0, 0x0)
    <empty stack>

Abort trap: 6

$ otool -lL venv1/lib/python3.5/site-packages/kerberos.cpython-35m-darwin.so | grep -i clang
	@rpath/libclang_rt.asan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
         name @rpath/libclang_rt.asan_osx_dynamic.dylib (offset 24)
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib/darwin (offset 12)
$
```

**Comment by dreness** [comment]
@hmijail Have you tried temporarily disabling the pip package cache (--no-cache-dir)? It might be using a previously built version, perhaps one that was built with an older xcode. When I install pykerberos with the pip cache disabled, I can see clang being invoked (tip: try newproc.d instead of execsnoop).

Trimmed newproc.d output:
```
/Users/local/venv/bin/python3.5 /Users/local/venv/bin/pip3 install --no-cache-dir kerberos
/bin/sh -c uname -p 2> /dev/null
uname -p
/Users/local/venv/bin/python3.5 -c import setuptools, tokenize;__file__='/private/var/folders/cv/ft1m5cd53nb0xjqmfydwl1lr0000gn/T/pip-build-bkxklbpa/kerberos/setup (...) egg_info 
…
/bin/sh /usr/bin/krb5-config --cflags gssapi
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic <...>
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic <...>
…
```

Checking the various time stamps shows expected results as well:
```
f="%m%t%S"
# accessed / modified / created
$ stat -f "${f}a%n${f}m%n${f}c%n" kerberos.cpython-35m-darwin.so 
1475449563	Oct  2 16:15:19 2016
1475449563	Oct  2 16:06:03 2016
1475449563	Oct  2 16:06:03 2016
```

Your pip output is consistent with what you'd see when installing from cache:
```
# no cache
$ pip3 install --no-cache-dir kerberos
Collecting kerberos
  Downloading kerberos-1.2.5.tar.gz
Installing collected packages: kerberos
  Running setup.py install for kerberos ... done
Successfully installed kerberos-1.2.5

# with cache
$ pip3 install kerberos
Collecting kerberos
Installing collected packages: kerberos
Successfully installed kerberos-1.2.5
```
You can check for old wheels by looking inside the cache directory (which is used by default, even from a virtualenv). On a mac, try:
```
find ~/Library/Caches/pip/wheels -name "kerberos*" -ls
```

**Comment by hmijail** [comment]
Oh gosh. You're right, it was cached by pip, and looks like the cached version had been built with the CFLAGS that I happened to have configured the day it got cached.

Thank you very much, I guess this issue can be closed. 

As a side issue: I'm trying now to think how could I have avoided this problem, and why I didn't find this kind of problem before in other package managers. To me it looks like a bad pip quirk, but again, I'm no Python expert. 
So, if you are and you would say this is a pip issue, I will try reporting it.

**Comment by dreness** [comment]
Glad this fixed it for you. I guess the pip audience includes both "users" and "developers", so it's fair to assume that not everyone knows all the details of how it works. If you want to file a bug against pip, I might suggest that the pip output could say "Installing from cache" when using a previously built version, if that would have helped you pinpoint this problem.

**Comment by hmijail** [comment]
Thank you for the suggestion, but I just realized that pip actually already says "using cache". 
```
$ pip install  pykerberos
Collecting pykerberos
  Using cached pykerberos-1.1.13.tar.gz
Installing collected packages: pykerberos
  Running setup.py install for pykerberos ... done
Successfully installed pykerberos-1.1.13
$
```

So I guess that the only solution is to pay attention... and actually know what pip might be doing at each step.
Sigh.
