### ISSUE TITLE
The execution time cost of authenticate_gss_client_step varies in a big range like 0~10 seconds？

### ISSUE THREAD

**Issue by apli** [apple/ccs-pykerberos#53]
In most time, it costs only milliseconds for authenticate_gss_client_init to return.Sometimes, less than 1 percentage, it takes 5 seconds to 10 seconds. 
In authenticate_gss_client_init, gss_init_sec_context costs most time.
Why?

**Comment by dreness** [comment]
Is there any pattern here, such as the amount of time between the longer-duration calls? Also what platform are you using? Anything special about your Kerberos configuration?

**Comment by apli** [comment]
I tested the calls one by one,and sometimes it took long time.
The platform is ubuntu 12.04.Nothing is special of config, I think,
kdc_timeout = 2500
clockskew = 300
use_dns_lookup = 0
udp_preference_limit = 1465
max_retries = 3
dns_lookup_kdc = false
dns_lookup_realm = false
renewable = false
forwardable = false
renew_lifetime = 0m
max_renewable_life = 30m

What could affect the time cost?

**Comment by apli** [comment]
by adding log print I found gssint_import_internal_name,

**Comment by apli** [comment]
by adding log print I found the function gssint_import_internal_name,

**Comment by apli** [comment]
By adding log print I found the statement in the function gssint_import_internal_name cost long:
         status = mech->gss_import_name(minor_status, union_name->external_name,
				       union_name->name_type, internal_name);

**Comment by dreness** [comment]
@apli That sounds kind of like it might be stalling in DNS lookups (unrelated to dns_lookup_kdc or dns_lookup_realm).

When you're doing the testing, are you using the same inputs every time? If you are seeing wide variance with the same inputs, I would be looking towards things like DNS record TTLs or maybe kerberos ticket lifetime. One thing you could do is watch for DNS requests (using tcpdump or whatever) to see if there are external DNS queries that align with the slow calls. An occasionally slow external resolver (or congested network along the path to it) could result in this sort of behavior. Also I'm reading some stuff about gss_import_name that suggests that if the form of the input is such that a hostname is expected, and is absent, the local host is used. Sometimes machines have multiple DNS entries (perhaps via /etc/hosts) for 'localhost'. Maybe one of them resolves to an IPv6 address, but some portion of your stack is not v6 capable.

By the same token (heyo, kerberos puns), an external KDC may be occasionally slow in granting a TGT, or any other network interaction for that matter - but if so I wouldn't expect that slowness to show up under gss_import_name.

**Comment by apli** [comment]
@dreness Thanks a lot.
You're right.It's related to the DNS lookups .I think it's the response cost of the DNS server that causes the problem. I  repeated the test  after commentting the DNS server in DNS config, and the long-time calls never showed up.

In fact ,I don't need  a DNS  server to do the DNS  lookup for the kdc address is configured in /etc/hosts and not registered in the DNS server.Seems it still use DNS server first.When the DNS server response slowly the long-time call shows up.

Is there any way to use /etc/hosts first?
The order in /etc/nsswitch.conf of my machine is hosts: files dns.

**Comment by apli** [comment]
@dreness 
Problem solved. After your advice , I used tcpdump to watch DNS requests，I found the DNS request for the host of the principle which is not in /etc/hosts. 
Thanks again!

**Comment by dreness** [comment]
You're welcome! Glad you fixed it.
