### ISSUE TITLE
Cannot build or install from pip due to krb5-config

### ISSUE THREAD

**Issue by ltoshea** [apple/ccs-pykerberos#66]
> ccs-pykerberos-master]$ python setup.py build
running build
running build_ext
building 'kerberos' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/base64.c -o build/temp.linux-x86_64-2.7/src/base64.o sh: krb5-config: command not found

I've tried installing from pip and also get the same issues. It looks like under the dependencies section it lists in setup.py it lists 'krb5-config' which looks like it might be in the library "gssapi"

What do I need to install to fix this dependency?

**Comment by ltoshea** [comment]
Turns out I just needed to install "krb5-config" onto the box via the standard OS repo.

**Comment by gregorydulin** [comment]
I also had to install gcc

`sudo apt-get install gcc`

**Comment by NicolasPA** [comment]
This was also my error trying to install `kerberos` in Docker from `python:3.10-slim`.  
As in the previous comments, I had to install both `libkrb5-dev` and `gcc `.

```bash
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y \
        libkrb5-dev \
        gcc \
    && pip install kerberos
```
