### ISSUE TITLE
_HOST in principal is not supported

### ISSUE THREAD

**Issue by normal-cock** [apple/ccs-pykerberos#74]
I have two hbase thrift server behind a tcp load balance proxy. I want to use `_HOST` in principal so that it will be replaced with the actual hostname of the running instance. However, I got the following error when using `_HOST`:
`(('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server hbase/_host@SFG.COM not found in Kerberos database', -1765328377))`

Here is my code.

    import kerberos
    _, context = kerberos.authGSSClientInit(service='hbase@_HOST', principal='') 
    kerberos.authGSSClientStep(context, '')

**Comment by CloudDU** [comment]
Hi, did you have solve this problem, I have the same one
